Container Start/Stop Implementation

diff --git a/.github/workflows/users-service-ci-cd.yml b/.github/workflows/users-service-ci-cd.yml
--- a/.github/workflows/users-service-ci-cd.yml
+++ b/.github/workflows/users-service-ci-cd.yml
@@ -51,14 +51,33 @@ jobs:
       # THIS IS WHERE PROD VARS N TEST VARS ARE DEFINED N USED BASED ON BRANCH RUNNING FROM
       id: builder_pusher
       env:   # here we r creating env vars n assigning values to them.
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         ECR_REGISTRY: ${{ steps.ecr-login-id.outputs.registry }}
         ECR_REPOSITORY: users-service-test
         IMAGE_TAG: ${{github.run_id}}
+        TEMPORARY_CONTAINER: $(date +%s)
         ECS_CLUSTER: traderapp_dev   # Amazon ECS cluster name
         ECS_SERVICE: userssrvc-ecs-service-test # Your Amazon ECS service name
 
       run: |
         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+        
+        #now lets start the container to run the image built above.........
+        echo "our temporary container name is : $TEMPORARY_CONTAINER
+        if ! docker run -d --name $TEMPORARY_CONTAINER -e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -p 80:80 $IMAGE_TAG; then
+          # Now let's display the logs of the running container
+          docker logs $TEMPORARY_CONTAINER
+          echo "Failed to start the container. Stopping the workflow..."
+          exit 1  # Set a non-zero exit code to stop the workflow
+
+        else
+          echo "Container started successfully. Proceeding with the workflow..."  
+          
+        #now lets stop the server/container
+        run: docker stop $TEMPORARY_CONTAINER
+
+        #its time to push the image to ECR:
         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
         echo "::set-output name=built_image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
 #end of CI
